### ISSUE TITLE
5人以上ルームに入ってる状態で開始すると途中でバグる

### ISSUE THREAD

**Issue by Yoshiaki-Apple** [ssl-gunma-univ/Park-Design#6]
パッと思いつく解決案

1. ルームに入れるのを4人までにする

2. 5人以上入った場合でも表示されるようにコードを書き換える
例えば**user.left  user.top user.right**を自分以外に3人より多い表示ができるように書き換える

**Comment by NakamRay** [comment]
ゲームに入れるのを4人までにしました．
本当は6人ぐらいまでは一緒にプレイできるようにしたいですが，レイアウトの都合や時間の都合でこのような仕様にしました．
