### ISSUE TITLE
ゲーム開始された状態で途中で誰かが入場すると...

### ISSUE THREAD

**Issue by Yoshiaki-Apple** [ssl-gunma-univ/Park-Design#9]
プレーリードッグした際にNaNとなり必ず失敗してしまう。

一応、次のラウンドから正常にプレイはできる。

**Comment by NakamRay** [comment]
ダメージが蓄積されるルールなので，途中参加はしないでしょう．
ということで，ゲーム中（playing === true）のときはルームに入れないようにしました．
